name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - 'qdon-glitch-beta'
      - 'qdon-glitch'
    tags:
      - '*'
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/mastodon
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=raw,value=beta,enable=${{ github.ref == format('refs/heads/{0}', 'qdon-glitch-beta') }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=edge,branch=qdon-glitch-beta
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/mastodon:buildcache-${{ github.ref_name }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/mastodon:buildcache-${{ github.ref_name }},mode=max
